Add @Named to the PrettyTimeProducer.produce() producer method
quarkiverse/quarkus-prettytime pull request #5
Opened 2021-03-11 08:48 UTC by mkouba

- resolves #4

2021-03-11 08:55 UTC, gsmet requested changes
Added a small comment and a big question :).

2021-03-11 08:55 UTC, gsmet commented on runtime/src/main/java/io/quarkiverse/prettytime/PrettyTimeProducer.java
> +    @Named("pretty")
I think it should be named `prettyTime`.

2021-03-11 08:55 UTC, gsmet commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
This doesn't look very thread safe to me? TBH, that was my main question when I saw this was a singleton, how thread safe it would be.

2021-03-11 11:14 UTC, mkouba commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
Well, the `PrettyTime` object is mutable and locale and ref are volatile fields. I think that it's ok to share the instance accross multiple threads unless you modify the state frequently...

2021-03-11 11:15 UTC, mkouba commented on runtime/src/main/java/io/quarkiverse/prettytime/PrettyTimeProducer.java
> +    @Named("pretty")
Ok, why not.

2021-03-11 11:17 UTC, mkouba commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
That said, we could change the scope e.g. to `@Dependent` but then there is no reason to inject the instance compared to `new PrettyTime()`.

2021-03-11 11:32 UTC, gsmet commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
Yes exactly and that's my problem. For me you will probably change the object pretty often if you share it across your app and I don't see how making it a singleton bean will work at all.

The fact that the fields are volatile doesn't mean it will be consistent with what you want to do at a given place if another thread changes it.

But maybe I'm missing something.

2021-03-11 11:58 UTC, mkouba commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
> For me you will probably change the object pretty often if you share it across your app...

I don't think that it's a common use case to change the `PrettyTime` instance... usually what you do is call the `format()` methods to get the formatted value for a particular date/time instance.

> The fact that the fields are volatile doesn't mean it will be consistent with what you want to do at a given place if another thread changes it.

Of course it won't but at least the change should be propagated at some point ;-)

> But maybe I'm missing something.

You're not. It's a good point. Unfortunately, I'm not aware of an easy solution. 

We could:
1. Remove the producer completely, but then we should find a new justification for the existence of this extension.
2. Change the scope - `@RequestScoped` should work in _most_ cases, `@Dependent` does not make a lot of sense...
3. Wrap the `PrettyTime` instance in some immutable container

2021-03-11 12:05 UTC, gsmet commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
Well your example with locales is a good real-life one.

Let's take two examples:
- web page with a locale
- emails generated in several locales and sent to various users

There are two real life examples that wouldn't work very well with this approach.

I really think having a singleton bean is a bad idea and will lead to lots of errors. And even a request scoped bean is dangerous IMHO. There's no point in providing something that lead to dangerous behaviors (that you might miss in your tests cause you don't have a ton of concurrent requests).

Now maybe I'm just being too cautious but I really fear this will lead to a lot of issues.

2021-03-11 12:19 UTC, mkouba commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
For non-default locales we should probably support cached `PrettyTime` instances, which can be achieved via custom qualifiers or something like `PrettyTimeProvider#get(Locale locale)`.

> Now maybe I'm just being too cautious but I really fear this will lead to a lot of issues.

Like I said in that case I see no justification for this extension... On the other hand, I think that it's really a great candidate for a Qute integration.

@gastaldi WDYT?

2021-03-11 13:05 UTC, gastaldi commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
Ah, I didn't know that `PrettyTime` was mutable. I always thought that if you needed a different locale you would use the constructor for that. In that case I agree that it shouldn't be a `Singleton` anymore. 

Caching `PrettyTime` instances per Locale won't work either since the object is still mutable, unless we return a subclass/proxied object that invalidates the cached version when `setLocale` is invoked?

2021-03-11 13:06 UTC, gastaldi commented on runtime/src/main/java/io/quarkiverse/prettytime/PrettyTimeProducer.java
> +    @Named("pretty")
Agreed, `prettyTime` looks better

2021-03-11 13:09 UTC, mkouba commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
> ...unless we return a subclass/proxied object that invalidates the cached version when setLocale is invoked?

No pls :-)

2021-03-11 13:14 UTC, gastaldi commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
Yeah, I think it's easier to make it `@Dependent`

2021-03-11 13:25 UTC, gastaldi commented on runtime/src/main/java/io/quarkiverse/prettytime/PrettyTimeProducer.java
> +    @Named("pretty")
```suggestion
    @Named("prettyTime")
```

2021-03-11 13:27 UTC, gastaldi commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +                    .addAsResource(new StringAsset("{inject:pretty.format(time)}"), "templates/pretty.txt"));
```suggestion
                    .addAsResource(new StringAsset("{inject:prettyTime.format(time)}"), "templates/pretty.txt"));
```

2021-03-11 13:33 UTC, gastaldi commented
I created https://github.com/quarkiverse/quarkus-prettytime/issues/6 for the Singleton case and committed the fix proposals in this PR. 

@mkouba mind adding a small description in the README about this feature?

2021-03-11 13:44 UTC, mkouba commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
Just FYI my guess would be that ~ 70% of all `@Singleton`/`@ApplicationScoped` beans in the wild are mutable and not thread-safe ;-).

2021-03-11 13:59 UTC, gastaldi commented on deployment/src/test/java/io/quarkiverse/prettytime/test/PrettyTimeQuteTest.java
> +        prettyTime.setLocale(Locale.ENGLISH);
@mkouba BTW the extension exists because of https://github.com/quarkiverse/quarkus-prettytime/blob/main/deployment/src/main/java/io/quarkiverse/prettytime/deployment/PrettyTimeProcessor.java#L18-L21, which is required to build to native

2021-03-12 08:41 UTC, gastaldi approved these changes

2021-03-12 08:45 UTC, merged